### ISSUE TITLE
Score Calculation Issue

### ISSUE THREAD

**Issue by lynnl87** [OPLabVanderbilt/ov_demo#1]
The points assigned here are 2, 1, and 0.
https://github.com/OPLabVanderbilt/ov_demo/blob/071d7557f91b69a3797513fc49db86c4bb7d3c61/index.html#L309-L317
However the logic here is checking for 0, 0.5, and 1. Correct answers on the robot portion aren't calculated (set as 2). 
https://github.com/OPLabVanderbilt/ov_demo/blob/071d7557f91b69a3797513fc49db86c4bb7d3c61/index.html#L330

Should the points in the on_finish function be assigned 1, 0.5, and 0 (correct, close, wrong)?

**Comment by JasonKChow** [comment]
You're right, thanks for noticing. Fixed.
